import { moduleMetadata, Story, Meta } from '@storybook/angular';
import { PtgNgxDatatableComponent } from './ptg-ngx-datatable.component';
import { PtgNgxDatatableModule } from '../ptg-ngx-datatable.module';
import { GRID_DATA } from '@ptg-angular-app/mock/grid-data';


export default {
  title: 'Component/PtgNgxDatatableComponent',
  component: PtgNgxDatatableComponent,
  decorators: [
    moduleMetadata({
      imports: [PtgNgxDatatableModule],
    }),
  ],
} as Meta<PtgNgxDatatableComponent>;

const Template: Story<PtgNgxDatatableComponent> = (
  args: PtgNgxDatatableComponent
) => ({
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const ScrollbarV = Template.bind({});
ScrollbarV.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const ScrollbarH = Template.bind({});
ScrollbarH.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const HeaderHeight = Template.bind({});
HeaderHeight.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const FooterHeight = Template.bind({});
FooterHeight.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const RowHeight = Template.bind({});
RowHeight.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const LoaderShowWhen = Template.bind({});
LoaderShowWhen.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const Offset = Template.bind({});
Offset.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const Limit = Template.bind({});
Limit.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};



export const ExternalSorting = Template.bind({});
ExternalSorting.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};

export const RowClass = Template.bind({});
RowClass.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};


export const ShowFiter = Template.bind({});
ShowFiter.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};

export const ShowActionButton = Template.bind({});
ShowActionButton.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};

export const ActionButtonLabel = Template.bind({});
ActionButtonLabel.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};

export const ActionButtonHeaderLabel = Template.bind({});
ActionButtonHeaderLabel.args = {
  columns :[
    { name: "Athlete", field: "athlete", frozenLeft: true},
    { name: "Age",field: "age",filtering: true },
    { name: "Country" ,field: "country",filtering: false},
    { name: "Year",field: "year",filtering: false },
    { name: "Date",field: "date" ,filtering: false},
    { name: "Sport",field: "sport" ,filtering: false},
    { name: "Gold",field: "gold" ,filtering: false},
    { name: "Silver",field: "silver" ,filtering: false},
    { name: "Total",field: "total" ,filtering: false},
  ],
  rows:GRID_DATA,
  scrollbarV: false,
  scrollbarH: false,
  headerHeight: 50,
  footerHeight: 100,
  rowHeight: 'auto',
  loaderShowWhen: false,
  limit: 4,
  externalSorting: false,
  rowClass: '',
  showFiter: true,
  selected: [],
  showActionButton: false,
  actionButtonLabel: 'Click Here',
  actionButtonHeaderLabel: 'Action',
  // offset: 0,
  // totalCount: 100,
  // virtualization: true,
  // externalPaging: false,
  // selectionType: this.SelectionType.checkbox,
};




